//ACCOUNT
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

//CART
export const CLEAR_CART = "CLEAR_CART"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const INCREMENT_PRODUCT = "INCREMENT_PRODUCT"
export const DECREMENT_PRODUCT = "DECREMENT_PRODUCT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS"